config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  devise_for :users
  
  root "home#index"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: {message: "must have title"}, uniqueness: true
  validates_presence_of :body, message: "must be present"
  default_scope{ order("created_at DESC") }
  before_save :capitalize_title

  def capitalize_title
    self.title.capitalize!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :tickets

  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}".squeeze(" ").strip
    else
      email
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_ticket, only: [:edit, :update, :destroy] 

  def index 
    @ticket = Ticket.new
    @tickets = Ticket.limit(10)
  end

  def create 
    respond_to do |format|
      @ticket = current_user.tickets.new(ticket_attributes)
      
      if @ticket.save 
        format.html{redirect_to tickets_path, notice: "Your ticket was created successfully!"}
        format.js{ render }
      else
        flash.now[:error] = "Please correct the form" 
        format.html{render :new}
        format.js { render js: "alert('you must fill in all the fields');" }
      end
    end

  end

  def show 
    @ticket   = Ticket.find params[:id]
  end

  def edit
  end

  def new
    @ticket = Ticket.new
  end

  def update
    respond_to do |format|
      if @ticket.update_attributes(ticket_attributes)
        if params.has_key? :page
          format.html{redirect_to tickets_path}
          format.js { render }
        else
          format.html{redirect_to @ticket, notice: "ticket updated successfully"}
        end
      else
        flash.now[:error] = "couldn't update"
        render :edit
      end
    end
  end

  def destroy
    if @ticket.destroy
      redirect_to tickets_path, notice: "quesiton deleted successfully"
    else
      redirect_to tickets_path, notice: "we had trouble deleting"
    end
  end


  private

  def find_ticket
    @ticket = current_user.tickets.find params[:id]
    redirect_to root_path, notice: "Access Denined" unless @ticket
  end

  def ticket_attributes
    params.require(:ticket).permit([:title, :body, :status]) # this requires the ticket object
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    date.strftime("%Y-%b-%d") 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/home/index.html.haml
%h2 HOME

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tickety
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      - if flash[:notice]
        %h3.bg-success= flash[:notice]
      - if flash[:error]
        %h3.bg-danger= flash[:notice]
    .container
      %br/
      = link_to "Home", tickets_path, class: "btn btn-default"
      / = link_to "New", new_ticket_path, class: "btn btn-default"
      

      - if user_signed_in?
        %span
          Hello #{current_user.full_name}
        = link_to "Sign Out", destroy_user_session_path, class: "btn btn-default", method: :delete
      - else
        = link_to "Sign In", new_user_session_path, class: "btn btn-default"
      = yield

app/views/tickets/_form.html.haml
- if @ticket.errors.any?
  %ul
    - @ticket.errors.full_messages.each do |message|
      %li= message

= simple_form_for @ticket, html: {class: "form-horizontal"} do |f|
  = f.input :title, label: "ticket title"
  = f.input :body, label: "ticket body"
  = f.submit (@ticket.persisted? ? "Update" : "Save")

app/views/tickets/_remoteform.html.haml
= simple_form_for @ticket, html: {class: "form-horizontal"}, remote: true do |f|
  = f.input :title, label: "ticket title"
  = f.input :body, label: "ticket description"
  = f.submit (@ticket.persisted? ? "Update" : "Save")

app/views/tickets/_ticket.html.haml
%div{id: dom_id(@ticket)}
  %h2= link_to @ticket.title, @ticket
  / default will be ticket_path if we pass in ticket
  %p= @ticket.body
  %p
    Created On: #{formatted_date(@ticket.created_at)}
  %p
    Updated On: #{formatted_date(@ticket.updated_at)}
  - if ticket.status
    %p= button_to "Mark Un-Resolved", ticket_path(ticket, :ticket => { :status => 0 }, page: "index"), method: :patch, remote: true, class: "btn btn-danger btn-status"
  - else
    %p= button_to "Mark Resolved", ticket_path(ticket, :ticket => { :status => 1 }, page: "index"), method: :patch, remote: true, class: "btn btn-success btn-status"
  %hr/

app/views/tickets/create.js.haml
$(".ticket-container").prepend("#{j render 'ticket', ticket: @ticket}");
$("##{dom_id(@ticket)}").hide().fadeIn(500);

$(".modal-dialog").find(".close").click();
$(".modal-dialog").find("textarea").val("");
$(".modal-dialog").find("input[type='text']").val("");



/ - @answer = @question.answers.new
/ $("#answer-form").html("#{j render 'form'}");
/ $("#answer_body").val("");

app/views/tickets/edit.html.haml
%h1 Edit Question

= render "form"

app/views/tickets/index.html.haml
/ Modal
/ Button trigger modal
%button.btn.btn-primary{"data-target" => "#myModal", "data-toggle" => "modal"}
  New Ticket
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} x
        %h4#myModalLabel.modal-title Create a New Ticket
      .modal-body
        = simple_form_for @ticket, html: {class: "form-horizontal"}, remote: true do |f|
          = f.input :title, label: "ticket title"
          = f.input :body, label: "ticket description"
          = f.submit (@ticket.persisted? ? "Update" : "Save")
%h1 Listing all the tickets
.ticket-container
  - @tickets.each do |ticket|
    %div{id: dom_id(ticket)}
      %h2= link_to ticket.title, ticket
      / default will be ticket_path if we pass in ticket
      %p= ticket.body
      %p
        Created On: #{formatted_date(ticket.created_at)}
      %p
        Updated On: #{formatted_date(ticket.updated_at)}
      - if ticket.status
        %p= button_to "Mark Un-Resolved", ticket_path(ticket, :ticket => { :status => 0 }, page: "index"), method: :patch, remote: true, class: "btn btn-danger btn-status"
      - else
        %p= button_to "Mark Resolved", ticket_path(ticket, :ticket => { :status => 1 }, page: "index"), method: :patch, remote: true, class: "btn btn-success btn-status"
      %hr/
  

app/views/tickets/new.html.haml
%h1 Created New Ticket
= render "form"

app/views/tickets/show.html.haml
/ = debug @ticket # for debugging 
%h1= @ticket.title
%p= @ticket.body
%p= formatted_date(@ticket.created_at)


= link_to "edit", edit_ticket_path(@ticket)
%br/
= link_to "delete", @ticket, method: :delete, data: {confirm: "are you sure?"}

app/views/tickets/update.js.haml
var $status = $("body").find("##{dom_id(@ticket)}").find(".btn-status");$(function(){if ( $status.hasClass("btn-danger") ){$status.attr("class","btn btn-status btn-success").val("Mark Resolved");}else{$status.attr("class","btn btn-status btn-danger").val("Mark Un-Resolved");}});